version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api_lw
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=lw
      - JWT_SECRET=lw
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

  database:
    image: postgres:15
    container_name: postgres_db_lw
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lw
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
